include:
  # - ./AI_Based_Detector/compose.yml
  # - ./AI-Correlation/compose.yml
  # - ./Anomaly-Detectors/compose.yml
  - ./IoB/docker-compose.yml
  - ./MISP_Server-docker/docker-compose.yml     #Deployed in advanced with script due to dependencies with other components
  # - ./PP-CTI/compose.yaml
  - ./Threat-Hunting-And-Forensics/DFIR/docker-compose.yml
  - ./Threat-Hunting-And-Forensics/THF/docker-compose.yml
  - ./wazuh-docker/compose.yaml      #Deployed in advanced with script due to dependencies with other components